name = input("Enter your name: ")
gender = input("Enter your gender F/M: ")
year_of_birth = int(input("Enter Year Of Birth: "))
class_ = input("Enter your class: ")
print("------ Student Profile ------")
print("Name: ", name)
print("Gender: ", gender)
print("Age: ", str(2025 - year_of_birth))
print("Class: ", class_)

